name: Commit Lint and Versioning

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4

  generate-version:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: commitlint
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install semantic-release
        run: npm install -g semantic-release @semantic-release/git @semantic-release/github conventional-changelog-conventionalcommits

      - name: Generate version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
